#!/usr/bin/env bash
# Install nginx server and change index.html page to show text, Hello World!

# Update package list and install Nginx
sudo apt update
sudo apt install -y nginx

# Configure Nginx to listen on port 80
sudo sh -c 'echo "server {
    listen 80;
        server_name localhost;

	    location / {
	            root /var/www/html;
		            index index.html;
			        }

		}" > /etc/nginx/sites-available/default'

	# Create index.html with "Hello World!" content
	sudo sh -c 'echo Hello World! > /var/www/html/index.html'
	# echo "Hello World!" > /usr/share/nginx/html/index.html

		# Restart Nginx
		sudo service nginx restart
