#!/usr/bin/env bash

# Install and configure HAproxy on load balancing lb-01 server

# Install necessary packages
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.4
sudo apt-get update
sudo apt-get -y install haproxy

# Enable HAProxy to be managed via init script
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

# Backup the original HAProxy configuration file
sudo mv /etc/haproxy/haproxy.cfg{,.original}

# Define the new HAProxy configuration
new_config="global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server 95218-web-01 100.26.174.177:80 check
    server 95218-web-02 52.23.213.217:80 check"

# Apply the new configuration
echo "$new_config" | sudo tee /etc/haproxy/haproxy.cfg > /dev/null

# Restart HAProxy service to apply the changes
sudo service haproxy restart
